mybatis:
  typeAliasesPackage: com.gf.entity
  mapperLocations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mvc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
